### ISSUE TITLE
9_gelu.cu code wrong

### ISSUE THREAD

**Issue by amnesiahzd** [RussWong/CUDATutorial#1]
https://github.com/RussWong/CUDATutorial/blob/main/9_gelu.cu#L67

acording to the gelu formula, there should be only two __hmul12 in the outermost layer
and  after commenting the original code, the compilation will also fail

i think here is one version of correct codes
//const half2 y2 = __hmul2(__hmul2(__float2half2_rn(0.5F), x2),
//                                         __hadd2(__float2half2_rn(1.0F), __float22half2_rn(tanh_out)));

**Comment by Zhiwei35** [comment]
thanks for the issue, you are right, I wrote one more hmul2. I did not validate half2 gelu at that time, cause I have no Ampere GPU on hands.

**Comment by amnesiahzd** [comment]
thx for your review
